### PR TITLE
Create chromecdp.go

### PR DESCRIPTION
**Pull request by ghost**
Added a Golang chromium automation

### CODE REVIEW

**Comment by debpalash** [comment]
> Added a Golang chromium automation

Thanks for PR. a simple installation instruction as comment would be nice tho.

**Comment by pneb** [comment]
# Installation of chromedp
```sh
go get -u github.com/chromedp/chromedp
```

# Installation of open-golang
```sh
go get github.com/skratchdot/open-golang/open
```

# Usage
```sh
go run <>.go
```

**Comment by debpalash** [comment]
> # Installation of chromedp
> ```
> go get -u github.com/chromedp/chromedp
> ```
> 
> # Installation of open-golang
> ```
> go get github.com/skratchdot/open-golang/open
> ```
> 
> # Usage
> ```
> go run <>.go
> ```

isn't ‘go get’ in module mode is deprecated. for 1.19/latest?

**Comment by pneb** [comment]
Oh yeah, they have to create a configuration and build it then.

**Comment by debpalash** [comment]
> 

okay merging,
although it would be a better if we do separate repo inside https://github.com/noCaptchaAi for scripts with deps and configs.

**Comment by pneb** [comment]
Yep. I'll start making repository once I'm healed. Thanks for understanding me 🙂

**Comment by debpalash** [comment]
> Yep. I'll start making repository once I'm healed. Thanks for understanding me 🙂

yes please. get recovered soon 🤟🏽

**Pull request merged**
